#!/bin/python

import time
import os
import signal
import sys

SURE_TO_QUIT = False


def on_windows_change(*args):
    print("La fenettre a changé de taille")


def on_sigint(*args):
    global SURE_TO_QUIT
    if SURE_TO_QUIT:
        sys.exit(2)
    print("Etes vous sur ?")
    SURE_TO_QUIT = True


def on_kill(*args):
    print("Je veux vivre!")


signal.signal(signal.SIGWINCH, on_windows_change)
signal.signal(signal.SIGINT, on_sigint)
# signal.signal(signal.SIGKILL, on_kill)


def main():
    pid = os.getpid()
    compteur = 1
    while True:
        print(f"salut - mon pid est {pid} - {compteur}")
        compteur += 1
        time.sleep(1)


main()
