#!/bin/python

import time
import os


def main():
    pid = os.getpid()
    compteur = 1
    while True:
        print(f"salut ! - mon pid est {pid} - {compteur}")
        compteur += 1
        time.sleep(1)


main()
