#!/bin/python

import random
import sys


def main():
    args = sys.argv

    if len(args) != 2:
        print("Invalid number of arguments")
        sys.exit(2)

    head_or_tails = sys.argv[1]
    if head_or_tails not in ("head", "tails"):
        print("Choose between head or tail")
        sys.exit(2)

    flip = random.choice(["head", "tails"])

    if flip == head_or_tails:
        print(flip, " - you win")
    if flip != head_or_tails:
        print(flip, " - you loose")
        sys.exit(1)


if __name__ == "__main__":
    main()
