#!/bin/python

import random
import sys


def main():
    args = sys.argv

    if len(args) != 2:
        print("Pas le bon nombre d'arguments")
        sys.exit(2)

    pile_ou_face = sys.argv[1]
    if pile_ou_face not in ("pile", "face"):
        print("Tapez 'pile' ou 'face'")
        sys.exit(2)

    tir = random.choice(["pile", "face"])

    if tir == pile_ou_face:
        print(tir, " -  gagné")
        sys.exit(0)
    if tir != pile_ou_face:
        print(tir, " - perdu")
        sys.exit(1)


if __name__ == "__main__":
    main()
