#!/bin/python

import time
import os
import signal
import sys

SURE_TO_QUIT = False


def on_windows_change(*args):
    print("Window changed size")


def on_sigint(*args):
    global SURE_TO_QUIT
    if SURE_TO_QUIT:
        sys.exit(2)
    print("Are you sure?")
    SURE_TO_QUIT = True


def on_kill(*args):
    print("I want to survive")


signal.signal(signal.SIGWINCH, on_windows_change)
signal.signal(signal.SIGINT, on_sigint)
# signal.signal(signal.SIGKILL, on_kill)


def main():
    pid = os.getpid()
    count = 1
    while True:
        print(f"my pid is {pid} - {count}")
        count += 1
        time.sleep(1)


main()
